---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/scripts/upload-properties.sh


params:
  CONFIG_SERVER_USERNAME:
  CONFIG_SERVER_PASSWORD:
  CONFIG_SERVER_URI:
